version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5553:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: fastapi_app
    env_file:
      - .env
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8888 ${DEBUG:+--reload}"
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

    restart: unless-stopped

volumes:
  postgres_data: